version: '3.5'
services:
  postgres:
    container_name: s3-replica
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - PGDATA:/data/postgres/attendance
    volumes:
      - postgres-db:/data/postgres/attendance
    ports:
      - "8181:5432"
volumes:
  postgres-db:
    driver: local